version: '3.8'

services:
  askahuman:
    build:
      context: .
      dockerfile: AskAHuman/Dockerfile
    ports:
      - "80:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings:MariaDB=server=database;port=3306;database=askahuman;user=root;password=sml12345"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mariadb:11.1.4
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - "MARIADB_ROOT_PASSWORD=sml12345"
      - "MARIADB_DATABASE=askahuman"
    volumes:
      - /backup-volume:/backup
      - ./DatabaseLayer/Docs/script.sql:/docker-entrypoint-initdb.d/ddl.sql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h 127.0.0.1 -u root --password=sml12345 -e 'SELECT 1'"]
      interval: 2s
      timeout: 5s
      retries: 20